CANDIDATOS = [
    "Gabriel Vilugrón (GVG)",
    "Carlos Abogabir (1A)",
    "Antonia Ríos (1A)",
    "Cristóbal Mingo (Solidaridad)",
    "Tomás Vásquez (Solidaridad)",
    "Victoria Trejo (NAU)",
    "Max Weldt (Avanzar)"
]

PROPUESTAS = [
    # --- ACADEMIA Y CARGA CURRICULAR ---
    {"eje": "Academia y Carga Curricular", "texto": "Levantar datos territoriales sobre reprobación en ramos críticos.[cite: 6]", "candidatos": ["Victoria Trejo (NAU)"]},
    {"eje": "Academia y Carga Curricular", "texto": "Almuerzos Temáticos por Major con profesores.[cite: 6]", "candidatos": ["Victoria Trejo (NAU)"]},
    {"eje": "Academia y Carga Curricular", "texto": "Levantar datos reales sobre la baja presencialidad para exigir soluciones a la Escuela.[cite: 5]", "candidatos": ["Victoria Trejo (NAU)"]},
    {"eje": "Academia y Carga Curricular", "texto": "Programas al día: reunir el programa real de cada ramo.[cite: 12]", "candidatos": ["Cristóbal Mingo (Solidaridad)", "Tomás Vásquez (Solidaridad)"]},
    {"eje": "Academia y Carga Curricular", "texto": "Consolidación y modernización del Drive Solidario.[cite: 12, 23]", "candidatos": ["Cristóbal Mingo (Solidaridad)", "Tomás Vásquez (Solidaridad)"]},
    {"eje": "Academia y Carga Curricular", "texto": "Fundamentals Solidario: recopilación de ejercicios.[cite: 12, 23]", "candidatos": ["Cristóbal Mingo (Solidaridad)", "Tomás Vásquez (Solidaridad)"]},
    {"eje": "Academia y Carga Curricular", "texto": "Plataforma académica integral (mallas, recomendaciones).[cite: 19]", "candidatos": ["Tomás Vásquez (Solidaridad)"]},
    {"eje": "Academia y Carga Curricular", "texto": "Apuntes solidarios con encargados por asignatura.[cite: 19]", "candidatos": ["Tomás Vásquez (Solidaridad)"]},
    {"eje": "Academia y Carga Curricular", "texto": "Ayudantías y repasos masivos pre-certamen.[cite: 19]", "candidatos": ["Tomás Vásquez (Solidaridad)"]},
    {"eje": "Academia y Carga Curricular", "texto": "Velar por cupos asegurados en ramos de plan común.[cite: 32]", "candidatos": ["Carlos Abogabir (1A)", "Antonia Ríos (1A)"]},
    {"eje": "Academia y Carga Curricular", "texto": "Drive académico 2.0 renovado.[cite: 32]", "candidatos": ["Carlos Abogabir (1A)", "Antonia Ríos (1A)"]},
    {"eje": "Academia y Carga Curricular", "texto": "Generación de resúmenes automáticos de ramos.[cite: 32]", "candidatos": ["Carlos Abogabir (1A)", "Antonia Ríos (1A)"]},
    {"eje": "Academia y Carga Curricular", "texto": "Cápsulas de estudios en YouTube.[cite: 32]", "candidatos": ["Carlos Abogabir (1A)", "Antonia Ríos (1A)"]},
    {"eje": "Academia y Carga Curricular", "texto": "Ayudantías de pares para ramos difíciles.[cite: 45]", "candidatos": ["Max Weldt (Avanzar)"]},
    {"eje": "Academia y Carga Curricular", "texto": "Garantizar respeto total a la identidad frente a docentes.[cite: 45]", "candidatos": ["Max Weldt (Avanzar)"]},
    {"eje": "Academia y Carga Curricular", "texto": "Red de apuntes y Ayudantías Transversales.[cite: 51]", "candidatos": ["Gabriel Vilugrón (GVG)"]},
    {"eje": "Academia y Carga Curricular", "texto": "Nube de Apuntes Unificada y Colaborativa por Major.[cite: 51]", "candidatos": ["Gabriel Vilugrón (GVG)"]},
    {"eje": "Academia y Carga Curricular", "texto": "Canal de Youtube (Nivelación y Fundamentals).[cite: 51]", "candidatos": ["Gabriel Vilugrón (GVG)"]},
    {"eje": "Academia y Carga Curricular", "texto": "Plataforma Web 'Major Match'.[cite: 52]", "candidatos": ["Gabriel Vilugrón (GVG)"]},
    {"eje": "Academia y Carga Curricular", "texto": "Guías para uso de Herramientas Curriculares (Plazip, BuscaCursos).[cite: 52]", "candidatos": ["Gabriel Vilugrón (GVG)"]},
    {"eje": "Academia y Carga Curricular", "texto": "Lineamientos sobre uso de Inteligencia Artificial.[cite: 52]", "candidatos": ["Gabriel Vilugrón (GVG)"]},
    {"eje": "Academia y Carga Curricular", "texto": "Integrar Programas de Cursos en BuscaRamos.[cite: 52]", "candidatos": ["Gabriel Vilugrón (GVG)"]},
    {"eje": "Academia y Carga Curricular", "texto": "Ciclos de conversación 'Hablemos de Ingeniería'.[cite: 53]", "candidatos": ["Gabriel Vilugrón (GVG)"]},

    # --- VIDA UNIVERSITARIA Y COMUNIDAD ---
    {"eje": "Vida Universitaria y Comunidad", "texto": "Encuentros al aire libre ('Vuelta al Patio').[cite: 4]", "candidatos": ["Victoria Trejo (NAU)"]},
    {"eje": "Vida Universitaria y Comunidad", "texto": "Calendario Cultural de hitos históricos y científicos.[cite: 5]", "candidatos": ["Victoria Trejo (NAU)"]},
    {"eje": "Vida Universitaria y Comunidad", "texto": "Semana de la Memoria (septiembre).[cite: 5]", "candidatos": ["Victoria Trejo (NAU)"]},
    {"eje": "Vida Universitaria y Comunidad", "texto": "Feria 'Exponiendo la UC' de áreas extracurriculares.[cite: 18]", "candidatos": ["Tomás Vásquez (Solidaridad)"]},
    {"eje": "Vida Universitaria y Comunidad", "texto": "Calendario solidario de Ingeniería actualizado.[cite: 18]", "candidatos": ["Tomás Vásquez (Solidaridad)"]},
    {"eje": "Vida Universitaria y Comunidad", "texto": "Guía '¿Qué me faltó como novato?'[cite: 18]", "candidatos": ["Tomás Vásquez (Solidaridad)"]},
    {"eje": "Vida Universitaria y Comunidad", "texto": "Jornadas de descompresión post-evaluaciones.[cite: 20]", "candidatos": ["Tomás Vásquez (Solidaridad)"]},
    {"eje": "Vida Universitaria y Comunidad", "texto": "Actividades y campeonatos intergeneracionales.[cite: 20]", "candidatos": ["Tomás Vásquez (Solidaridad)"]},
    {"eje": "Vida Universitaria y Comunidad", "texto": "Reconocimiento al 'Estudiante del mes'.[cite: 20]", "candidatos": ["Tomás Vásquez (Solidaridad)"]},
    {"eje": "Vida Universitaria y Comunidad", "texto": "Torneos multiformato (deportivos, videojuegos, mesa).[cite: 20]", "candidatos": ["Tomás Vásquez (Solidaridad)"]},
    {"eje": "Vida Universitaria y Comunidad", "texto": "Activaciones de patio periódicas.[cite: 36]", "candidatos": ["Carlos Abogabir (1A)", "Antonia Ríos (1A)"]},
    {"eje": "Vida Universitaria y Comunidad", "texto": "Torneos UC (deportivos y videojuegos).[cite: 36]", "candidatos": ["Carlos Abogabir (1A)", "Antonia Ríos (1A)"]},
    {"eje": "Vida Universitaria y Comunidad", "texto": "Cafe Concert con bandas de Ingeniería.[cite: 36]", "candidatos": ["Carlos Abogabir (1A)", "Antonia Ríos (1A)"]},
    {"eje": "Vida Universitaria y Comunidad", "texto": "Vitrina de logros de la facultad.[cite: 36]", "candidatos": ["Carlos Abogabir (1A)", "Antonia Ríos (1A)"]},
    {"eje": "Vida Universitaria y Comunidad", "texto": "Convenios segmentados con la Tarjeta TUC.[cite: 36]", "candidatos": ["Carlos Abogabir (1A)", "Antonia Ríos (1A)"]},
    {"eje": "Vida Universitaria y Comunidad", "texto": "Apoyo 'Impulsa tu proyecto' para clubes.[cite: 37]", "candidatos": ["Carlos Abogabir (1A)", "Antonia Ríos (1A)"]},
    {"eje": "Vida Universitaria y Comunidad", "texto": "Almuerza con tu CF.[cite: 37]", "candidatos": ["Carlos Abogabir (1A)", "Antonia Ríos (1A)"]},
    {"eje": "Vida Universitaria y Comunidad", "texto": "Almuerzos novatos.[cite: 37]", "candidatos": ["Carlos Abogabir (1A)", "Antonia Ríos (1A)"]},
    {"eje": "Vida Universitaria y Comunidad", "texto": "Recomendaciones de OFG en el patio.[cite: 37]", "candidatos": ["Carlos Abogabir (1A)", "Antonia Ríos (1A)"]},
    {"eje": "Vida Universitaria y Comunidad", "texto": "Ligas y torneos regulares y casuales (Spikeball, Poker, etc.).[cite: 46]", "candidatos": ["Max Weldt (Avanzar)"]},
    {"eje": "Vida Universitaria y Comunidad", "texto": "Vitrina para bandas y artistas en el patio.[cite: 46]", "candidatos": ["Max Weldt (Avanzar)"]},
    {"eje": "Vida Universitaria y Comunidad", "texto": "Torneos de Básquetbol y Fútbol.[cite: 53]", "candidatos": ["Gabriel Vilugrón (GVG)"]},
    {"eje": "Vida Universitaria y Comunidad", "texto": "Liga Interna de Ajedrez con ranking ELO.[cite: 53]", "candidatos": ["Gabriel Vilugrón (GVG)"]},
    {"eje": "Vida Universitaria y Comunidad", "texto": "Ligas semestrales de E-Sports.[cite: 53]", "candidatos": ["Gabriel Vilugrón (GVG)"]},
    {"eje": "Vida Universitaria y Comunidad", "texto": "Torneo Integration Bee.[cite: 53]", "candidatos": ["Gabriel Vilugrón (GVG)"]},
    {"eje": "Vida Universitaria y Comunidad", "texto": "Semanas Temáticas de Campus (Cine, etc.).[cite: 54]", "candidatos": ["Gabriel Vilugrón (GVG)"]},
    {"eje": "Vida Universitaria y Comunidad", "texto": "Tardes de Deporte Comunitario y Pantalla Abierta.[cite: 54]", "candidatos": ["Gabriel Vilugrón (GVG)"]},
    {"eje": "Vida Universitaria y Comunidad", "texto": "Juego de escenario '¿Qué Dice Ingeniería?'.[cite: 54]", "candidatos": ["Gabriel Vilugrón (GVG)"]},
    {"eje": "Vida Universitaria y Comunidad", "texto": "Batallas de freestyle y acústicos (Expresión en el Patio).[cite: 54]", "candidatos": ["Gabriel Vilugrón (GVG)"]},
    {"eje": "Vida Universitaria y Comunidad", "texto": "Proyecto visual y literario 'IngeniARTE'.[cite: 55]", "candidatos": ["Gabriel Vilugrón (GVG)"]},

    # --- SALUD MENTAL Y BIENESTAR ---
    {"eje": "Salud Mental y Bienestar", "texto": "Tutoría Ingeniera (Apoyo 1 a 1 para novatas).[cite: 4]", "candidatos": ["Victoria Trejo (NAU)"]},
    {"eje": "Salud Mental y Bienestar", "texto": "Talleres de habilidades para la vida y gestión del estrés.[cite: 21]", "candidatos": ["Tomás Vásquez (Solidaridad)"]},
    {"eje": "Salud Mental y Bienestar", "texto": "Respiro Ing (café y pausas en semanas de pruebas).[cite: 35]", "candidatos": ["Carlos Abogabir (1A)", "Antonia Ríos (1A)"]},
    {"eje": "Salud Mental y Bienestar", "texto": "Acompañamiento 'CT al patio' antes de pruebas.[cite: 36]", "candidatos": ["Carlos Abogabir (1A)", "Antonia Ríos (1A)"]},
    {"eje": "Salud Mental y Bienestar", "texto": "Red de orientación y protocolo de salud mental.[cite: 48]", "candidatos": ["Max Weldt (Avanzar)"]},
    {"eje": "Salud Mental y Bienestar", "texto": "Juegos y café para descanso en semanas de pruebas.[cite: 48]", "candidatos": ["Max Weldt (Avanzar)"]},
    {"eje": "Salud Mental y Bienestar", "texto": "Red de apoyo para estudiantes de región.[cite: 48]", "candidatos": ["Max Weldt (Avanzar)"]},
    {"eje": "Salud Mental y Bienestar", "texto": "Café con el CT semanal.[cite: 48]", "candidatos": ["Max Weldt (Avanzar)"]},
    {"eje": "Salud Mental y Bienestar", "texto": "Ayudantes de Bienestar en ramos de FMAT y Física.[cite: 55]", "candidatos": ["Gabriel Vilugrón (GVG)"]},
    {"eje": "Salud Mental y Bienestar", "texto": "Protocolo de Salud Mental vinculante.[cite: 55]", "candidatos": ["Gabriel Vilugrón (GVG)"]},
    {"eje": "Salud Mental y Bienestar", "texto": "Red de apoyo a regiones, LOAF UC y carpool.[cite: 55, 56]", "candidatos": ["Gabriel Vilugrón (GVG)"]},

    # --- INFRAESTRUCTURA Y GESTIÓN ---
    {"eje": "Infraestructura, Seguridad y Administración", "texto": "Ruta para tu idea: sitio que reúna herramientas como Horario UC.[cite: 10]", "candidatos": ["Cristóbal Mingo (Solidaridad)"]},
    {"eje": "Infraestructura, Seguridad y Administración", "texto": "Banco de ideas: tablero abierto de problemas a resolver.[cite: 11]", "candidatos": ["Cristóbal Mingo (Solidaridad)"]},
    {"eje": "Infraestructura, Seguridad y Administración", "texto": "Habla con la DIPRE: Panel de seguimiento público.[cite: 12, 23]", "candidatos": ["Cristóbal Mingo (Solidaridad)", "Tomás Vásquez (Solidaridad)"]},
    {"eje": "Infraestructura, Seguridad y Administración", "texto": "Portal de inquietudes académicas para la DIPRE.[cite: 19]", "candidatos": ["Tomás Vásquez (Solidaridad)"]},
    {"eje": "Infraestructura, Seguridad y Administración", "texto": "Exigir control de acceso con credencial (TUC) en salas.[cite: 22]", "candidatos": ["Tomás Vásquez (Solidaridad)"]},
    {"eje": "Infraestructura, Seguridad y Administración", "texto": "Canal de reportes directos de mantenimiento.[cite: 22]", "candidatos": ["Tomás Vásquez (Solidaridad)"]},
    {"eje": "Infraestructura, Seguridad y Administración", "texto": "Página/bot de Preguntas frecuentes UC.[cite: 32]", "candidatos": ["Carlos Abogabir (1A)", "Antonia Ríos (1A)"]},
    {"eje": "Infraestructura, Seguridad y Administración", "texto": "Buzón CF para inquietudes.[cite: 33]", "candidatos": ["Carlos Abogabir (1A)", "Antonia Ríos (1A)"]},
    {"eje": "Infraestructura, Seguridad y Administración", "texto": "Explicativo claro de 'Becas al día'.[cite: 33]", "candidatos": ["Carlos Abogabir (1A)", "Antonia Ríos (1A)"]},
    {"eje": "Infraestructura, Seguridad y Administración", "texto": "Exigir reparación de cámaras en Estacionamientos Seguros.[cite: 35]", "candidatos": ["Carlos Abogabir (1A)", "Antonia Ríos (1A)"]},
    {"eje": "Infraestructura, Seguridad y Administración", "texto": "Mochila Segura: broches en mesas de estudio.[cite: 35]", "candidatos": ["Carlos Abogabir (1A)", "Antonia Ríos (1A)"]},
    {"eje": "Infraestructura, Seguridad y Administración", "texto": "Red de apoyo administrativo.[cite: 45]", "candidatos": ["Max Weldt (Avanzar)"]},
    {"eje": "Infraestructura, Seguridad y Administración", "texto": "Exigir mejoras en baños, aseo, ascensores y enchufes.[cite: 56]", "candidatos": ["Gabriel Vilugrón (GVG)"]},

    # --- ROL PÚBLICO E IMPACTO SOCIAL ---
    {"eje": "Rol Público, Desarrollo y Empleabilidad", "texto": "Continuidad a Operaciones Sociales.[cite: 5]", "candidatos": ["Victoria Trejo (NAU)"]},
    {"eje": "Rol Público, Desarrollo y Empleabilidad", "texto": "Red de Apoyo y recorridos para estudiantes secundarios.[cite: 5]", "candidatos": ["Victoria Trejo (NAU)"]},
    {"eje": "Rol Público, Desarrollo y Empleabilidad", "texto": "Asesoría para postular a fondos concursables.[cite: 18]", "candidatos": ["Tomás Vásquez (Solidaridad)"]},
    {"eje": "Rol Público, Desarrollo y Empleabilidad", "texto": "Ciclo 'Almuerzo con...' docentes y profesionales.[cite: 21]", "candidatos": ["Tomás Vásquez (Solidaridad)"]},
    {"eje": "Rol Público, Desarrollo y Empleabilidad", "texto": "Mes de la solidaridad con fundaciones.[cite: 30]", "candidatos": ["Carlos Abogabir (1A)", "Antonia Ríos (1A)"]},
    {"eje": "Rol Público, Desarrollo y Empleabilidad", "texto": "InnovatING para visibilizar a estudiantes en investigación.[cite: 30]", "candidatos": ["Carlos Abogabir (1A)", "Antonia Ríos (1A)"]},
    {"eje": "Rol Público, Desarrollo y Empleabilidad", "texto": "Convenios de Inteligencia Artificial (ej. Cursor).[cite: 31]", "candidatos": ["Carlos Abogabir (1A)", "Antonia Ríos (1A)"]},
    {"eje": "Rol Público, Desarrollo y Empleabilidad", "texto": "Cursos y talleres 'IngenierIA'.[cite: 31]", "candidatos": ["Carlos Abogabir (1A)", "Antonia Ríos (1A)"]},
    {"eje": "Rol Público, Desarrollo y Empleabilidad", "texto": "Organización de Hackathones UC.[cite: 31]", "candidatos": ["Carlos Abogabir (1A)", "Antonia Ríos (1A)"]},
    {"eje": "Rol Público, Desarrollo y Empleabilidad", "texto": "Iniciativa 'Ing al servicio' (alfabetización, reforzamiento).[cite: 34]", "candidatos": ["Carlos Abogabir (1A)", "Antonia Ríos (1A)"]},
    {"eje": "Rol Público, Desarrollo y Empleabilidad", "texto": "Campañas de recolección de invierno y verano.[cite: 34]", "candidatos": ["Carlos Abogabir (1A)", "Antonia Ríos (1A)"]},
    {"eje": "Rol Público, Desarrollo y Empleabilidad", "texto": "Trayectoria con sentido: charlas con egresados.[cite: 34]", "candidatos": ["Carlos Abogabir (1A)", "Antonia Ríos (1A)"]},
    {"eje": "Rol Público, Desarrollo y Empleabilidad", "texto": "Banco de ofertas y apoyo para prácticas atractivas.[cite: 35]", "candidatos": ["Carlos Abogabir (1A)", "Antonia Ríos (1A)"]},
    {"eje": "Rol Público, Desarrollo y Empleabilidad", "texto": "CV Check Flash con ayudantes y profesionales.[cite: 35]", "candidatos": ["Carlos Abogabir (1A)", "Antonia Ríos (1A)"]},
    {"eje": "Rol Público, Desarrollo y Empleabilidad", "texto": "Ferias de emprendimientos.[cite: 47]", "candidatos": ["Max Weldt (Avanzar)"]},
    {"eje": "Rol Público, Desarrollo y Empleabilidad", "texto": "Conexiones con empresas, ONGs o fundaciones.[cite: 47]", "candidatos": ["Max Weldt (Avanzar)"]},
    {"eje": "Rol Público, Desarrollo y Empleabilidad", "texto": "Campaña de reciclaje de hardware para colegios.[cite: 47]", "candidatos": ["Max Weldt (Avanzar)"]},
    {"eje": "Rol Público, Desarrollo y Empleabilidad", "texto": "Participación en Feria de Ciencias UC.[cite: 54]", "candidatos": ["Gabriel Vilugrón (GVG)"]},

    # --- COMUNIDAD Y PARTICIPACIÓN ---
    {"eje": "Representación, Disidencias y Participación", "texto": "Impulsar representantes generacionales propios para LICC.[cite: 4]", "candidatos": ["Victoria Trejo (NAU)"]},
    {"eje": "Representación, Disidencias y Participación", "texto": "Difusión activa del Fondo de Apadrinamiento.[cite: 4]", "candidatos": ["Victoria Trejo (NAU)"]},
    {"eje": "Representación, Disidencias y Participación", "texto": "Día de la Mujer Ingeniera (Workshop y Trayectorias).[cite: 4]", "candidatos": ["Victoria Trejo (NAU)"]},
    {"eje": "Representación, Disidencias y Participación", "texto": "Continuidad a 'Mujeres que inspiran' y 'Cumbre de Mujeres Líderes'.[cite: 5]", "candidatos": ["Victoria Trejo (NAU)"]},
    {"eje": "Representación, Disidencias y Participación", "texto": "Intervención Mes Disidente con micro-relatos.[cite: 5]", "candidatos": ["Victoria Trejo (NAU)"]},
    {"eje": "Representación, Disidencias y Participación", "texto": "100 Voces de Ingeniería (entrevistas de diagnóstico).[cite: 12, 23]", "candidatos": ["Cristóbal Mingo (Solidaridad)", "Tomás Vásquez (Solidaridad)"]},
    {"eje": "Representación, Disidencias y Participación", "texto": "Cuenta pública mensual de votaciones y gestiones.[cite: 18]", "candidatos": ["Tomás Vásquez (Solidaridad)"]},
    {"eje": "Representación, Disidencias y Participación", "texto": "Resumen 'Consejo en simple' mensual.[cite: 33]", "candidatos": ["Carlos Abogabir (1A)", "Antonia Ríos (1A)"]},
    {"eje": "Representación, Disidencias y Participación", "texto": "Garantizar un espacio de convivencia seguro y sin prejuicios.[cite: 46]", "candidatos": ["Max Weldt (Avanzar)"]},
    {"eje": "Representación, Disidencias y Participación", "texto": "Visibilidad física y digital de votaciones.[cite: 48]", "candidatos": ["Max Weldt (Avanzar)"]}
]
